export enum BookingStatus {
  PENDING = "PENDING",
  PENDING_CHECKOUT = "PENDING_CHECKOUT",
  CONFIRMED = "CONFIRMED",
  CHECKED_IN = "CHECKED_IN",
  CHECKED_OUT = "CHECKED_OUT",
  CANCELLED = "CANCELLED",
}
