import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#004b71",
        "primary-container": "#BCE4FC",
        "on-secondary": "#ffffff",
        "surface-container-low": "#f0f4fa",
        "surface-container": "#EDEDF2",
        "secondary": "#7d5704",
        "on-tertiary-fixed": "#2f1400",
        "on-primary-container": "#00253B",
        "on-tertiary": "#ffffff",
        "surface-dim": "#F8FAFC",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#dfe3e9",
        "tertiary-fixed": "#ffdcc4",
        "primary": "#1594D8",
        "on-tertiary-fixed-variant": "#673d19",
        "on-background": "#181c20",
        "secondary-fixed-dim": "#f1be68",
        "on-primary-fixed": "#001e30",
        "inverse-on-surface": "#edf1f7",
        "on-primary": "#ffffff",
        "on-surface-variant": "#3f4850",
        "on-error-container": "#93000a",
        "tertiary": "#80512c",
        "outline-variant": "#bec7d2",
        "inverse-surface": "#2c3135",
        "on-secondary-fixed-variant": "#5f4100",
        "surface": "#f7f9ff",
        "primary-fixed": "#cfe5ff",
        "surface-container-highest": "#dfe3e9",
        "on-surface": "#181c20",
        "tertiary-container": "#9c6942",
        "inverse-primary": "#8fcdff",
        "secondary-fixed": "#ffdeab",
        "surface-tint": "#1594D8",
        "secondary-container": "#FDC972",
        "on-secondary-container": "#785300",
        "primary-fixed-dim": "#8fcdff",
        "on-error": "#ffffff",
        "surface-container-high": "#e5e8ee",
        "error-container": "#ffdad6",
        "error": "#EF4444",
        "tertiary-fixed-dim": "#f7ba8b",
        "on-tertiary-container": "#fffbff",
        "background": "#f7f9ff",
        "on-secondary-fixed": "#271900",
        "surface-bright": "#f7f9ff",
        "outline": "#E2E8F0",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "max-width": "1280px",
        gutter: "24px",
        "base-unit": "8px",
        "margin-desktop": "64px",
        "margin-mobile": "20px",
      },
      fontFamily: {
        "headline-sm": ["Poppins", "sans-serif"],
        "headline-lg": ["Poppins", "sans-serif"],
        "display-lg-mobile": ["Poppins", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Poppins", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "display-lg": ["Poppins", "sans-serif"],
      },
      fontSize: {
        "headline-sm": ["17px", { lineHeight: "1.4", fontWeight: "600" }],
        "headline-lg": ["36px", { lineHeight: "1.3", fontWeight: "600" }],
        "display-lg-mobile": ["40px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": ["28px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg": ["64px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};

export default config;
